### ISSUE TITLE
Enable pkg-config

### ISSUE THREAD

**Issue by tdegeus** [catchorg/Catch#1032]
It would be great to enable to use of pkg-config, in particular when non-standard install paths are used. The user can then simply compile with

```bash
$CXX ... `pkg-config --cflags catch` ...
```

instead of `-I/path/to/catch`.

To this end one would have to add the file `catch.pc.ic` to the root, with the following content

```bash
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}

Name: Catch
Description: Testing library for C++
Requires:
Version: @CATCH_VERSION_NUMBER@
Libs:
Cflags: -I${prefix}/@INCLUDE_INSTALL_DIR@
```

and add to `CMakeLists.txt`

```cmake
set(CATCH_VERSION_NUMBER ???)

if(NOT WIN32 OR NOT CMAKE_HOST_SYSTEM_NAME MATCHES Windows)

  set(PKGCONFIG_INSTALL_DIR
    "${CMAKE_INSTALL_DATADIR}/pkgconfig"
    CACHE PATH "Path where catch.pc is installed"
  )

  configure_file(catch.pc.in catch.pc @ONLY)

  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/cppmat.pc DESTINATION ${PKGCONFIG_INSTALL_DIR})

endif()
```

**Comment by horenmar** [comment]
I played with this a bit and after changing some details, it is in Catch 2 branch

**Comment by tdegeus** [comment]
Great! However, I think there is still one issue.

If I test it on my system, currently 

```bash
$ cmake /path/to/catch -DCMAKE_INSTALL_PREFIX:PATH=/test/path

$ pkg-config --cflags catch
-I/test/path/
```

while I need to feed the compiler with

``bash
-I/test/path/include/
```

One way to go could be to have the following `catch.pc.in` (I have successfully tested this on my system)

```cmake
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}

Name: Catch
Description: Testing library for C++
Requires:
Version: @CATCH_VERSION_NUMBER@
Libs:
Cflags: -I${prefix}/@INCLUDE_INSTALL_DIR@/include
```

There might be a more elegant solution. I did not look in great detail in the `CMakeLists.txt` to find if there is another solution there.

**Comment by horenmar** [comment]
@tdegeus We always copy the header into `include/catch`, so just adding `include` at the end of the include path seems reasonable.

**Comment by tdegeus** [comment]
@horenmar Great! Thanks a lot!
