### ISSUE TITLE
[Documentation] Trailing space in table of contents susceptible to removal

### ISSUE THREAD

**Issue by martinmoene** [catchorg/Catch#1048]
See [this remark](https://github.com/philsquared/Catch/commit/79b405fd3f752bd61a077d03798001c4e9d711b1#diff-76e731333fb756df3bff5ddb3b731c46L4).

**Comment by horenmar** [comment]
Yeah, I've setup my all my text editors to clean out trailing whitespace on save. I am going to take a look at the ToC script.

**Comment by horenmar** [comment]
I decided to append `<br>` to the ToC lines and regenerated already existing ToCs.
